export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST'
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS'
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL'

export const GET_TOPICS_REQUEST = 'GET_TOPICS_REQUEST'
export const GET_TOPICS_SUCCESS = 'GET_TOPICS_SUCCESS'
export const GET_TOPICS_FAIL = 'GET_TOPICS_FAIL'